### ISSUE TITLE
Incompatible with cookiecutter 1.4.0

### ISSUE THREAD

**Issue by stphivos** [benregn/cookiecutter-django-ansible#10]
Error info:
Unable to create file 'setup.py'
Error message: 'dict object' has no attribute 'full_name'

I had to downgrade cookiecutter to v1.3.0.

**Comment by Ivaylo-Bachvarov** [comment]
@stphivos 
I recently started a new cookiecutter-django-ansible project. You can find it here: https://github.com/HackSoftware/cookiecutter-django-ansible 

Any feedback is more then welcomed. :beers:
